### ISSUE TITLE
Error 400 trying to redeem sniped code

### ISSUE THREAD

**Issue by AllinolCP** [GiorgioBrux/nitro-sniper-enhanced#36]
![Screenshot_20210115-103904_Chrome](https://user-images.githubusercontent.com/56921534/104678431-03d72980-571e-11eb-9b03-457f5d16cfe0.png)

**Comment by bonxz** [comment]
I have also noticed this and since the last update, the fake codes are no longer recognised correctly. It tries to check many fake codes.

`2021-01-15T06:34:30.881029+00:00 app[worker.1]: [Nitro Sniper] (ERROR) Tried to redeem code [givenitropleaseiampoor] but got error: 400: Bad Request `

**Comment by GiorgioBrux** [comment]
> I have also noticed this and since the last update, the fake codes are no longer recognised correctly. It tries to check many fake codes.
> 
> `2021-01-15T06:34:30.881029+00:00 app[worker.1]: [Nitro Sniper] (ERROR) Tried to redeem code [givenitropleaseiampoor] but got error: 400: Bad Request `

Fixed the fake codes issue in dafbbe67f39b9964437ccc8a1cbfa787b46d53c2.

**Comment by bonxz** [comment]
> 
> 
> > I have also noticed this and since the last update, the fake codes are no longer recognised correctly. It tries to check many fake codes.
> > `2021-01-15T06:34:30.881029+00:00 app[worker.1]: [Nitro Sniper] (ERROR) Tried to redeem code [givenitropleaseiampoor] but got error: 400: Bad Request `
> 
> Fixed the fake codes issue in [dafbbe6](https://github.com/GiorgioBrux/nitro-sniper-enhanced/commit/dafbbe67f39b9964437ccc8a1cbfa787b46d53c2).

It still doesn't work properly.
Now, for example, it declared a code as fake but it was a real code.

`2021-01-15T12:12:52.006720+00:00 app[worker.1]: [Nitro Sniper] [+] Sniped [7aczqUzfUXamwC2j] - Fake Code - ***** from fitzo#****.`

![nitro](https://user-images.githubusercontent.com/61289944/104726549-270cd380-5734-11eb-8b98-9cedc9a59142.png)

**Comment by bonxz** [comment]
Also, the ms seconds no longer show in the log since the last or penultimate patch.

**Comment by GiorgioBrux** [comment]
@bonxz Big oof, sorry. Should be fixed 55f5011. The ms should still show on the errors where they matter. Will add them to all for consistency later.

**Comment by bonxz** [comment]
I think this hasn't been fixed properly yet. There are too many codes that just give a wrong result.
Like this again here
`2021-01-15T17:37:31.610092+00:00 app[worker.1]: [Nitro Sniper] [+] Sniped [8kwtsuA3CZmFg9mMd8Wrnays] - Fake Code - Microsoft Community from Michael Afton#2786.`
![nitro1](https://user-images.githubusercontent.com/61289944/104760400-9816b000-5761-11eb-8fe0-9c596b14af30.png)

But when I accept the gift, I get an error saying that the gift cannot be accepted. I haven't activated an XBOX code on this account yet, so what kind of code is it? And there is also no message that it has already been activated.
![nitro2](https://user-images.githubusercontent.com/61289944/104760500-bda3b980-5761-11eb-960f-762a5ff433f7.png)

**Comment by bonxz** [comment]
I think this hasn't been fixed properly yet. There are too many codes that just give a wrong result.
Like this again here
`2021-01-15T17:37:31.610092+00:00 app[worker.1]: [Nitro Sniper] [+] Sniped [8kwtsuA3CZmFg9mMd8Wrnays] - Fake Code - ***** from Michael Afton#****.`
![nitro1](https://user-images.githubusercontent.com/61289944/104760400-9816b000-5761-11eb-8fe0-9c596b14af30.png)

But when I accept the gift, I get an error saying that the gift cannot be accepted. I haven't activated an XBOX code on this account yet, so what kind of code is it? And there is also no message that it has already been activated.
![nitro2](https://user-images.githubusercontent.com/61289944/104760500-bda3b980-5761-11eb-960f-762a5ff433f7.png)
